default_stages:
  - pre-commit

repos:
    # -   repo: https://github.com/pre-commit/mirrors-mypy
    #     rev: v1.15.0
    #     hooks:
    #     -   id: mypy
    #         exclude: ^tests/
    #         additional_dependencies: [
    #           'sqlalchemy-stubs',
    #         ]
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: debug-statements
        -   id: detect-private-key
        -   id: mixed-line-ending
        -   id: check-merge-conflict
    -   repo: https://github.com/akaihola/darker
        rev: 1.7.2
        hooks:
        -   id: darker
            additional_dependencies:
            - black~=24.2.0
            - isort~=5.13.0
            args: ["--isort"]
    -   repo: https://github.com/pycqa/flake8
        rev: 7.1.1
        hooks:
        -   id: flake8
            additional_dependencies: [
                'flake8-debugger==3.2.1',
                'flake8-deprecated==1.3',
                'flake8-pep3101==1.2.1',
                'flake8-polyfill==1.0.2',
                'flake8-print==3.1.4',
                'flake8-string-format==0.2.3',
                'flake8-pyproject==1.2.3',
            ]
    -   repo: https://github.com/PyCQA/bandit
        rev: '1.8.3'
        hooks:
        - id: bandit
          args: ["-c", "pyproject.toml", "-r", "."]
          additional_dependencies: [".[toml]"]
