version: 2

sphinx:
   configuration: docs/conf.py

formats:
   - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
   version: 3.8
   install:
   - requirements: requirements/documentation.txt
