[tool.poetry]
name = "aiohttp_admin2"
version = "0.0.1"
description = "Generator an admin interface based on aiohttp."
authors = ["Mykhailo Havelia <misha.gavela@gmail.com>"]
maintainers = ["Mykhailo Havelia <misha.gavela@gmail.com>"]
license = "MIT"
readme = 'README_BUILD.rst'
homepage = "https://github.com/arfey/aiohttp_admin2"
repository = "https://github.com/arfey/aiohttp_admin2"
documentation = "https://aiohttp-admin2.readthedocs.io"
keywords = ["aiohttp_admin2", "admin interface", "aiohttp"]
packages = [
    { include = "aiohttp_admin2" },
    { include = "aiohttp_admin2/**/*" },
]
exclude = ["tests/**/*"]

[tool.poetry.dependencies]
python = "^3.7"
aiopg = "^1.3.0"
motor = "^2.4.0"
umongo = "^3.0.0"
sqlalchemy-stubs = "^0.4"
aiomysql = "^0.0.21"
aiohttp-jinja2 = "^1.4.2"
aiofiles = "^0.7.0"
python-dateutil = "^2.8.1"
SQLAlchemy = "1.3.24"
aiohttp = "3.6.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry-version-plugin]
source = "git-tag"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
