# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          # install poetry
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false

          # install deps
          pip install poetry-dynamic-versioning bandit twine
      - name: Create README.rst
        run: |
          cat README.rst > README_BUILD.rst && echo >> README_BUILD.rst && cat HISTORY.rst >> README_BUILD.rst
      - name: Publish
        run: |
          poetry build
          poetry run python -m twine check --strict dist/*
          poetry publish --username ${PYPI_USERNAME} --password ${PYPI_PASSWORD}
        env:
            PYPI_USERNAME: __token__
            PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
