name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip

          # install poetry
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

          # install deps
          pip install flake8 bandit twine

      - name: bandit
        run: make bandit

      - name: Lint build
        run: |
          source $HOME/.poetry/env

          cat README.rst > README_BUILD.rst && echo >> README_BUILD.rst && cat HISTORY.rst >> README_BUILD.rst
          poetry build
          python -m twine check --strict dist/*

  run-tests:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

          - name: Install Python dependencies
            run: |
              python -m pip install --upgrade pip

              # install deps
              pip install -r requirements/develop.txt

      - name: Pytest
        run: make test
